url: https://sheebabrema.github.io
baseurl: /living-yoga/

# Site settings
title: Sheeba Brema & Shehanaaz (Future Yoga Teacher)
description: .
show_downloads: false
google_analytics:
theme: jekyll-theme-slate

